apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  labels:
    app: echo-server
spec:
  selector:
    matchLabels:
     app: echo-server
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
        - name: server
          image: >-
            johann8384/echo-server:0.2@sha256:45b58a007e17eea15ebd86d2974a001cb28470922719a3cfdb78916c8fd3ccfb
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: JAEGER_SERVICE_NAME
              value: echo-server
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: JAEGER_AGENT_PORT
              value: 6831
            - name: JAEGER_AGENT_SOCKET_TYPE
              value: udp4
            - name: JAEGER_REPORTER_LOG_SPANS
              value: true
            - name: JAEGER_DISABLED
              value: false
            - name: https_PORT
              value: '8443'
            - name: http_PORT
              value: '8180'
          resources:
            requests:
              memory: 256M
              cpu: 1000m
            limits:
              memory: 512M
              cpu: 1200m
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname

