apiVersion: v1
kind: Service
metadata:
  name: echo-server
spec:
  selector:
    app: echo-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8180
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
